package com.hly.common.model;

import com.hly.common.model.base.BaseTrade;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Trade extends BaseTrade<Trade> {
	public static final Trade dao = new Trade().dao();
}
